
trigger:
  branches:
    include:
      - main

pr:
  branches:
    include:
      - main

variables:
  azureSubscription: 'fcba54f2-eb4d-4ac3-b705-42d3daaee2c2'
  # Function app name (without env-specific suffix)
  functionAppName: 'fnappdemo'
  
  # Agent VM image name
  vmImageName: 'ubuntu-latest'
  # Working Directory
  workingDirectory: '$(System.DefaultWorkingDirectory)/'

stages:
- stage: Build
  displayName: Build stage

  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: $(vmImageName)

    steps:
    - task: UsePythonVersion@0
      displayName: 'Use Python 3.10.12'
      inputs:
        versionSpec: 3.10.12 

    - bash: |
        pip install --target="./.python_packages/lib/site-packages" -r ./requirements.txt
      workingDirectory: $(workingDirectory)
      displayName: 'Install application dependencies'

    - task: ArchiveFiles@2
      displayName: 'Archive files'
      inputs:
        rootFolderOrFile: '$(workingDirectory)'
        includeRootFolder: false
        archiveType: zip
        archiveFile: $(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip
        replaceExistingArchive: true

    - publish: $(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip
      artifact: drop

- stage: Test
  displayName: Run Unit Tests
  dependsOn: Build
  condition: succeeded()

  jobs:
  - job: Test
    displayName: Test
    pool:
      vmImage: $(vmImageName)

    steps:
    - task: UsePythonVersion@0
      displayName: 'Use Python 3.10.12'
      inputs:
        versionSpec: 3.10.12 

    - task: CmdLine@2
      displayName: 'Run unit tests'
      inputs:
        script: |
          pip install -r requirements.txt
          pytest tests/

- stage: DeployDev
  displayName: Deploy to dev
  dependsOn: Test
  condition: and(succeeded(), ne(variables['Build.Reason'], 'PullRequest'))  

  jobs:
  - deployment: Deploy
    displayName: Deploy
    environment: 'development'
    pool:
      vmImage: $(vmImageName)

    strategy:
      runOnce:
        deploy:

          steps:
          - task: AzureFunctionApp@1
            displayName: 'Azure functions app deploy'
            inputs:
              azureSubscription: '$(azureSubscription)'
              resourceGroupName: $(functionAppName)-dev'
              appType: functionAppLinux
              appName: $(functionAppName)-dev
              package: '$(Pipeline.Workspace)/drop/$(Build.BuildId).zip'

- stage: DeployQA
  displayName: Deploy to qa
  dependsOn: DeployDev
  condition: succeeded()

  jobs:
  - deployment: Deploy
    displayName: Deploy
    environment: 'qa'
    pool:
      vmImage: $(vmImageName)

    strategy:
      runOnce:
        deploy:

          steps:
          - task: AzureFunctionApp@1
            displayName: 'Azure functions app deploy'
            inputs:
              azureSubscription: '$(azureSubscription)'
              resourceGroupName: $(functionAppName)-qa
              appType: functionAppLinux
              appName: $(functionAppName)-qa
              package: '$(Pipeline.Workspace)/drop/$(Build.BuildId).zip'

- stage: DeployProd
  displayName: Deploy to prod
  dependsOn: DeployQA
  condition: succeeded()

  jobs:
  - deployment: Deploy
    displayName: Deploy
    environment: 'production'
    pool:
      vmImage: $(vmImageName)

    strategy:
      runOnce:
        deploy:

          steps:
          - task: AzureFunctionApp@1
            displayName: 'Azure functions app deploy'
            inputs:
              azureSubscription: '$(azureSubscription)'
              resourceGroupName: $(functionAppName)-prod
              appType: functionAppLinux
              appName: $(functionAppName)-prod
              package: '$(Pipeline.Workspace)/drop/$(Build.BuildId).zip'
